version: '3.5'

services:
  postgres:
    container_name: dashboard_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /pgdata_within_container
    volumes:
      - ./pgdata:/pgdata_within_container
    ports:
      - "38746:5432"
