name: Docker Compose Check
on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and start Docker Compose
        run: |
          echo ---Building and starting up docker---
          docker compose up -d
          echo ---Containers up---
