name: dashoard check - backend
on: [push]
jobs:
  init:
    runs-on: docker-latest
    container:
      image: docker
      
    steps:
      - name: Update
        run: |
          apt-get update

      # - name: Install docker 
      #   run:  apt-get install -y docker-ce 

      - name: System docker 
        run: systemctl enable docker --now
      
      - name: Build and start Docker
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml -p testing up -d
          echo ---Containers up---
        
      - name: Run test
        run: |
          echo --- Running test cases ---
          docker-compose -f docker-compose.yml -p testing up --build --exit-code-from api-test
          echo --- Completed test cases ---