name: Excursion check - nmp test
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      
    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      
      - name: Build and start Docker
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml -p testing up -d
          echo ---Containers up---
        
      - name: Run test
        run: |
          echo --- Running test cases ---
          docker-compose -f docker-compose.yml -p testing up --build --exit-code-from api-test
          echo --- Completed test cases ---